package sorting;

import java.util.Arrays;

public class BubbleSort extends CommonUtility {
    public static void main(String[] args) {
        int[] arr = generateRandomArray(10);
        printArray(bubbleSortIDE(arr));
        printArray(bubbleSortSelf(arr));
        System.out.println("Are both matching? "+ Arrays.toString(bubbleSortIDE(arr)).equals(Arrays.toString(bubbleSortSelf(arr))));
    }
    // Generated by IDE
    public static int[] bubbleSortIDE(int[] arr) {
        int n = arr.length;
        for (int i = 0; i < n - 1; i++) {
            for (int j = 0; j < n - i - 1; j++) {
                if (arr[j] > arr[j + 1]) {
                    int temp = arr[j];
                    arr[j] = arr[j + 1];
                    arr[j + 1] = temp;
                }
            }
        }
        return arr;
    }

    public static int[] bubbleSortSelf(int[] arr) {
        int unsortedPartitionIndex = arr.length - 1;
        for (int i = 0; i < unsortedPartitionIndex; i++) {
            for (int j = 0; j < unsortedPartitionIndex - 1; j++) {
//                Stable sort algorithm - we swap only if j is greater than j+1.
                if (arr[j] > arr[j + 1]) {
                    swap(arr, arr[j], arr[j + 1]);
                }
            }
            unsortedPartitionIndex--;
        }
        return arr;
    }

}
